### Default String Configuration
### Add custom strings in custom/strings.yaml

# base config in partials/branding, partials/head
name: Lib
organization: Your Organization
icon: /assets/images/icon-logo.png
title: Library App
prettyName: Team Library

# partials/footer
helpText: Questions? Contact your organization's administrators.
defaultEmail: user@your_organization.com
footerButtons:
  edit: Edit This Page
  move: Move This Page
  create: Create New Page
  viewFolder: View Folder
  newDocLink: !!js/function (id) => `https://docs.google.com/document/create?usp=drive_web&folder=${id}`

# pages/categories, pages/index, partials/search
tagline: One place for your organization's documents.
viewAllButton: View All
faqLink: Get Started

# pages/move-file
moveFile:
  title: !!js/function (title) => `Move ${title}`
  prompt: !!js/function (title) => `Choose a folder to move '${title}' to`

# pages/search, partials/search
search:
  placeholder: Search...
  resultsTitle: !!js/function (query) => `Search results for ${query}`
  resultsKicker: !!js/function (query) => `Showing results for '${query}':`
  resultLabel:
    folder: !!js/function (path, folder) => `Filed under <a class="folder" href=${path}><span>${folder}</span></a>`
    person: !!js/function (lastUser) => `Last edited by <span class='author'>${lastUser}`
  noResults:
    kicker: !!js/function (query) => `There are no results for '${query}'`
    suggestion: To request a new page, contact your administrators.

# partials/sectionList
sectionHeading: "Table of Contents:"

#partials/siblingList
sibingHeading: Related Docs

# errors
error403:
  title: Operation Not Permitted
  heading: Not Authorized
  message: "<p>Check the request and try again. For assistance, contact #newstools.</p><p>Perhaps you'd like to search for something instead?</p>"
error404:
  title: Page Not Found
  heading: Whoops, that's a 404.
  message: Perhaps try to search for something else instead?
error500:
  title: Server Error
  heading: Uh oh, that's a 500.
  message: Perhaps try to search for something else instead?
