# Name of the app
name: Lib
icon: "https://***REMOVED***"
tagline: One place for your organization's documents.
search_placeholder: Search...
help_text: Questions? Contact your organization's administrators.